/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.highlighting


class StateConstraintTransitionColorSettingsPage extends StateConstraintTransitionBaseColorSettingsPage {
}
