/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea;

import com.google.inject.Injector;
import org.xtext.example.stateconstrainttransition.StateConstraintTransitionStandaloneSetupGenerated;

@SuppressWarnings("all")
public class StateConstraintTransitionStandaloneSetupIdea extends StateConstraintTransitionStandaloneSetupGenerated {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from StateConstraintTransitionIdeaModule to Module");
  }
}
