/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea;

import org.xtext.example.stateconstrainttransition.idea.AbstractStateConstraintTransitionIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class StateConstraintTransitionIdeaModule extends AbstractStateConstraintTransitionIdeaModule {
}
