/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea;

import com.google.inject.Injector;
import org.eclipse.xtext.ISetup;

@SuppressWarnings("all")
public class StateConstraintTransitionIdeaSetup implements ISetup {
  @Override
  public Injector createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
