/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.lang;

import org.xtext.example.stateconstrainttransition.idea.lang.AbstractStateConstraintTransitionFileType;

@SuppressWarnings("all")
public class StateConstraintTransitionFileType extends AbstractStateConstraintTransitionFileType {
  public final static StateConstraintTransitionFileType INSTANCE = new StateConstraintTransitionFileType();
  
  public StateConstraintTransitionFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(StateConstraintTransitionLanguage) is undefined");
  }
}
