/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.stateconstrainttransition.parser.antlr.internal.InternalStateConstraintTransitionParser;
import org.xtext.example.stateconstrainttransition.services.StateConstraintTransitionGrammarAccess;

public class StateConstraintTransitionParser extends AbstractAntlrParser {

	@Inject
	private StateConstraintTransitionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStateConstraintTransitionParser createParser(XtextTokenStream stream) {
		return new InternalStateConstraintTransitionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public StateConstraintTransitionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateConstraintTransitionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
