/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionLanguage;

public class StateConstraintTransitionCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public StateConstraintTransitionCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(StateConstraintTransitionLanguage.INSTANCE, psiModificationTracker);
	}

}
