/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.completion;

import org.xtext.example.stateconstrainttransition.idea.completion.AbstractStateConstraintTransitionCompletionContributor;

@SuppressWarnings("all")
public class StateConstraintTransitionCompletionContributor extends AbstractStateConstraintTransitionCompletionContributor {
  public StateConstraintTransitionCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor StateConstraintTransitionCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public StateConstraintTransitionCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
