/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.highlighting;

import org.xtext.example.stateconstrainttransition.idea.highlighting.StateConstraintTransitionBaseColorSettingsPage;

@SuppressWarnings("all")
public class StateConstraintTransitionColorSettingsPage extends StateConstraintTransitionBaseColorSettingsPage {
}
