/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class StateConstraintTransitionLanguage extends AbstractXtextLanguage {

	public static final StateConstraintTransitionLanguage INSTANCE = new StateConstraintTransitionLanguage();

	private StateConstraintTransitionLanguage() {
		super("org.xtext.example.stateconstrainttransition.StateConstraintTransition");
	}

}
