/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Composite State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.CompositeState#getConcernlevel <em>Concernlevel</em>}</li>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.CompositeState#getEndCompositeState <em>End Composite State</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getCompositeState()
 * @model
 * @generated
 */
public interface CompositeState extends State
{
  /**
   * Returns the value of the '<em><b>Concernlevel</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.ConcernLevel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Concernlevel</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concernlevel</em>' containment reference list.
   * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getCompositeState_Concernlevel()
   * @model containment="true"
   * @generated
   */
  EList<ConcernLevel> getConcernlevel();

  /**
   * Returns the value of the '<em><b>End Composite State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Composite State</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Composite State</em>' reference.
   * @see #setEndCompositeState(CompositeState)
   * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getCompositeState_EndCompositeState()
   * @model
   * @generated
   */
  CompositeState getEndCompositeState();

  /**
   * Sets the value of the '{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.CompositeState#getEndCompositeState <em>End Composite State</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Composite State</em>' reference.
   * @see #getEndCompositeState()
   * @generated
   */
  void setEndCompositeState(CompositeState value);

} // CompositeState
