/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getGlobalConstraint()
 * @model
 * @generated
 */
public interface GlobalConstraint extends Constraint
{
} // GlobalConstraint
