/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Constraint State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.SimpleConstraintState#getNewVariable <em>New Variable</em>}</li>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.SimpleConstraintState#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getSimpleConstraintState()
 * @model
 * @generated
 */
public interface SimpleConstraintState extends State
{
  /**
   * Returns the value of the '<em><b>New Variable</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.Variable}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>New Variable</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Variable</em>' containment reference list.
   * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getSimpleConstraintState_NewVariable()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getNewVariable();

  /**
   * Returns the value of the '<em><b>Constraint</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.Constraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' containment reference list.
   * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getSimpleConstraintState_Constraint()
   * @model containment="true"
   * @generated
   */
  EList<Constraint> getConstraint();

} // SimpleConstraintState
