/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Occurence</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateOccurence#getStateExpression <em>State Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getStateOccurence()
 * @model
 * @generated
 */
public interface StateOccurence extends EObject
{
  /**
   * Returns the value of the '<em><b>State Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State Expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Expression</em>' containment reference list.
   * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getStateOccurence_StateExpression()
   * @model containment="true"
   * @generated
   */
  EList<StateConstraint> getStateExpression();

} // StateOccurence
