/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage
 * @generated
 */
public interface StateConstraintTransitionFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StateConstraintTransitionFactory eINSTANCE = org.xtext.example.stateconstrainttransition.stateConstraintTransition.impl.StateConstraintTransitionFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>multiple</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>multiple</em>'.
   * @generated
   */
  multiple createmultiple();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition</em>'.
   * @generated
   */
  Transition createTransition();

  /**
   * Returns a new object of class '<em>Start Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Start Transition</em>'.
   * @generated
   */
  StartTransition createStartTransition();

  /**
   * Returns a new object of class '<em>End Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>End Transition</em>'.
   * @generated
   */
  EndTransition createEndTransition();

  /**
   * Returns a new object of class '<em>Full Transition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Full Transition</em>'.
   * @generated
   */
  FullTransition createFullTransition();

  /**
   * Returns a new object of class '<em>Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event</em>'.
   * @generated
   */
  Event createEvent();

  /**
   * Returns a new object of class '<em>Event Occurence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Event Occurence</em>'.
   * @generated
   */
  EventOccurence createEventOccurence();

  /**
   * Returns a new object of class '<em>State Occurence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Occurence</em>'.
   * @generated
   */
  StateOccurence createStateOccurence();

  /**
   * Returns a new object of class '<em>State Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Constraint</em>'.
   * @generated
   */
  StateConstraint createStateConstraint();

  /**
   * Returns a new object of class '<em>Composite State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Composite State</em>'.
   * @generated
   */
  CompositeState createCompositeState();

  /**
   * Returns a new object of class '<em>Concern Level</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Concern Level</em>'.
   * @generated
   */
  ConcernLevel createConcernLevel();

  /**
   * Returns a new object of class '<em>Simple Constraint State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Simple Constraint State</em>'.
   * @generated
   */
  SimpleConstraintState createSimpleConstraintState();

  /**
   * Returns a new object of class '<em>Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint</em>'.
   * @generated
   */
  Constraint createConstraint();

  /**
   * Returns a new object of class '<em>Variable Name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Name</em>'.
   * @generated
   */
  VariableName createVariableName();

  /**
   * Returns a new object of class '<em>Global Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global Constraint</em>'.
   * @generated
   */
  GlobalConstraint createGlobalConstraint();

  /**
   * Returns a new object of class '<em>group most least</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>group most least</em>'.
   * @generated
   */
  group_most_least creategroup_most_least();

  /**
   * Returns a new object of class '<em>group valuation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>group valuation</em>'.
   * @generated
   */
  group_valuation creategroup_valuation();

  /**
   * Returns a new object of class '<em>Max Min</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Max Min</em>'.
   * @generated
   */
  Max_Min createMax_Min();

  /**
   * Returns a new object of class '<em>var Enumeration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>var Enumeration</em>'.
   * @generated
   */
  varEnumeration createvarEnumeration();

  /**
   * Returns a new object of class '<em>Or state</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Or state</em>'.
   * @generated
   */
  Or_state createOr_state();

  /**
   * Returns a new object of class '<em>And state</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And state</em>'.
   * @generated
   */
  And_state createAnd_state();

  /**
   * Returns a new object of class '<em>state Name Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>state Name Ref</em>'.
   * @generated
   */
  stateNameRef createstateNameRef();

  /**
   * Returns a new object of class '<em>Log expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Log expr</em>'.
   * @generated
   */
  Log_expr createLog_expr();

  /**
   * Returns a new object of class '<em>Or expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Or expr</em>'.
   * @generated
   */
  Or_expr createOr_expr();

  /**
   * Returns a new object of class '<em>And expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And expr</em>'.
   * @generated
   */
  And_expr createAnd_expr();

  /**
   * Returns a new object of class '<em>Compare expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Compare expr</em>'.
   * @generated
   */
  Compare_expr createCompare_expr();

  /**
   * Returns a new object of class '<em>math expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>math expr</em>'.
   * @generated
   */
  math_expr createmath_expr();

  /**
   * Returns a new object of class '<em>Not</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not</em>'.
   * @generated
   */
  Not createNot();

  /**
   * Returns a new object of class '<em>Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constant</em>'.
   * @generated
   */
  Constant createConstant();

  /**
   * Returns a new object of class '<em>Var</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var</em>'.
   * @generated
   */
  Var createVar();

  /**
   * Returns a new object of class '<em>string</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string</em>'.
   * @generated
   */
  string createstring();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  StateConstraintTransitionPackage getStateConstraintTransitionPackage();

} //StateConstraintTransitionFactory
