/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage#getStateConstraint()
 * @model
 * @generated
 */
public interface StateConstraint extends EObject
{
} // StateConstraint
