/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.stateconstrainttransition.web.AbstractStateConstraintTransitionWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class StateConstraintTransitionWebModule extends AbstractStateConstraintTransitionWebModule {
  public StateConstraintTransitionWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
