/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class StateConstraintTransitionFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
