/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition;

import org.xtext.example.stateconstrainttransition.AbstractStateConstraintTransitionRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StateConstraintTransitionRuntimeModule extends AbstractStateConstraintTransitionRuntimeModule {
}
