/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class StateConstraintTransitionIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new StateConstraintTransitionStandaloneSetupIdea().createInjector
	}

}
