/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.stateconstrainttransition.StateConstraintTransitionRuntimeModule
import org.xtext.example.stateconstrainttransition.StateConstraintTransitionStandaloneSetupGenerated

class StateConstraintTransitionStandaloneSetupIdea extends StateConstraintTransitionStandaloneSetupGenerated {
	override createInjector() {
		val runtimeModule = new StateConstraintTransitionRuntimeModule()
		val ideaModule = new StateConstraintTransitionIdeaModule()
		val mergedModule = Modules2.mixin(runtimeModule, ideaModule)
		return Guice.createInjector(mergedModule)
	}
}
