/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.completion;

import org.eclipse.xtext.common.idea.completion.TerminalsCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractStateConstraintTransitionCompletionContributor extends TerminalsCompletionContributor {
	public AbstractStateConstraintTransitionCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
