/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionLanguage;

public class StateConstraintTransitionBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public StateConstraintTransitionBaseColorSettingsPage() {
		StateConstraintTransitionLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return StateConstraintTransitionLanguage.INSTANCE.getDisplayName();
	}
}
