/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.SemanticHighlightVisitor;
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionLanguage;

public class StateConstraintTransitionSemanticHighlightVisitor extends SemanticHighlightVisitor {
	public StateConstraintTransitionSemanticHighlightVisitor() {
		StateConstraintTransitionLanguage.INSTANCE.injectMembers(this);
	}
}
