/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionFileType;
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionLanguage;

public final class StateConstraintTransitionFileImpl extends BaseXtextFile {

	public StateConstraintTransitionFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, StateConstraintTransitionLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return StateConstraintTransitionFileType.INSTANCE;
	}
}
