/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.xtext.example.stateconstrainttransition.idea.lang.StateConstraintTransitionLanguage

class StateConstraintTransitionCompletionContributor extends AbstractStateConstraintTransitionCompletionContributor {
	new() {
		this(StateConstraintTransitionLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
