/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.stateconstrainttransition.stateConstraintTransition.GlobalConstraint;
import org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Global Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GlobalConstraintImpl extends ConstraintImpl implements GlobalConstraint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GlobalConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateConstraintTransitionPackage.Literals.GLOBAL_CONSTRAINT;
  }

} //GlobalConstraintImpl
