/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.stateconstrainttransition.stateConstraintTransition.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.stateconstrainttransition.stateConstraintTransition.Constraint;
import org.xtext.example.stateconstrainttransition.stateConstraintTransition.StateConstraintTransitionPackage;
import org.xtext.example.stateconstrainttransition.stateConstraintTransition.group_valuation;
import org.xtext.example.stateconstrainttransition.stateConstraintTransition.varEnumeration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>group valuation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.impl.group_valuationImpl#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.example.stateconstrainttransition.stateConstraintTransition.impl.group_valuationImpl#getAtomic <em>Atomic</em>}</li>
 * </ul>
 *
 * @generated
 */
public class group_valuationImpl extends GlobalConstraintImpl implements group_valuation
{
  /**
   * The cached value of the '{@link #getVar() <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVar()
   * @generated
   * @ordered
   */
  protected varEnumeration var;

  /**
   * The cached value of the '{@link #getAtomic() <em>Atomic</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtomic()
   * @generated
   * @ordered
   */
  protected Constraint atomic;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected group_valuationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateConstraintTransitionPackage.Literals.GROUP_VALUATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public varEnumeration getVar()
  {
    return var;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVar(varEnumeration newVar, NotificationChain msgs)
  {
    varEnumeration oldVar = var;
    var = newVar;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StateConstraintTransitionPackage.GROUP_VALUATION__VAR, oldVar, newVar);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVar(varEnumeration newVar)
  {
    if (newVar != var)
    {
      NotificationChain msgs = null;
      if (var != null)
        msgs = ((InternalEObject)var).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StateConstraintTransitionPackage.GROUP_VALUATION__VAR, null, msgs);
      if (newVar != null)
        msgs = ((InternalEObject)newVar).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StateConstraintTransitionPackage.GROUP_VALUATION__VAR, null, msgs);
      msgs = basicSetVar(newVar, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateConstraintTransitionPackage.GROUP_VALUATION__VAR, newVar, newVar));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Constraint getAtomic()
  {
    return atomic;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAtomic(Constraint newAtomic, NotificationChain msgs)
  {
    Constraint oldAtomic = atomic;
    atomic = newAtomic;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC, oldAtomic, newAtomic);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtomic(Constraint newAtomic)
  {
    if (newAtomic != atomic)
    {
      NotificationChain msgs = null;
      if (atomic != null)
        msgs = ((InternalEObject)atomic).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC, null, msgs);
      if (newAtomic != null)
        msgs = ((InternalEObject)newAtomic).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC, null, msgs);
      msgs = basicSetAtomic(newAtomic, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC, newAtomic, newAtomic));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StateConstraintTransitionPackage.GROUP_VALUATION__VAR:
        return basicSetVar(null, msgs);
      case StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC:
        return basicSetAtomic(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StateConstraintTransitionPackage.GROUP_VALUATION__VAR:
        return getVar();
      case StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC:
        return getAtomic();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StateConstraintTransitionPackage.GROUP_VALUATION__VAR:
        setVar((varEnumeration)newValue);
        return;
      case StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC:
        setAtomic((Constraint)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StateConstraintTransitionPackage.GROUP_VALUATION__VAR:
        setVar((varEnumeration)null);
        return;
      case StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC:
        setAtomic((Constraint)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StateConstraintTransitionPackage.GROUP_VALUATION__VAR:
        return var != null;
      case StateConstraintTransitionPackage.GROUP_VALUATION__ATOMIC:
        return atomic != null;
    }
    return super.eIsSet(featureID);
  }

} //group_valuationImpl
